### ISSUE TITLE
감염자 현황도 추가해주시면 좋겠습니다.

### ISSUE THREAD

**Issue by wonderlandpark** [Seia-Soto/maskd-releases#1]
현재 감염자 현황 (국가별, 성별, 나이별) 등등 다양한 감염자 수를 확인해볼 수 있으면 좋겠습니다.

**Comment by seia-soto** [comment]
해당 기능은 현재 비공개 프로젝트의 TODO에 존재합니다. 빠른 시일 내에 구현이 완료될 것으로 보입니다. 완료되면 현재 이슈에 추가 코멘트를 달아 알려드리겠습니다.

**Comment by Kadantte** [comment]
Well, gonna comment to be notfied too.

**Comment by seia-soto** [comment]
Closing all issues because the official source closed.
